---
title: "Towards a better understanding of the ocean copper distribution and speciation through a data-constrained global model"
collection: research
permalink: /research/CuModel
date: 2022-09-30
---

Copper (Cu) plays an essential role as a micronutrient for marine organisms, but it can also be toxic to phytoplankton when at elevated concentrations. Resolving the processes which control Cu biogeochemical cycling is therefore necessary to a complete understanding of how Cu impacts ocean life and biogeochemistry. Here we investigate the importance of various Cu cycling processes using a new global ocean Cu biogeochemical model. The model utilizes OCIM circulation and is constrained by global ocean Cu data from the GEOTRACES program. Biogeochemical processes incorporated into the model include sources from rivers, aerosol dust deposition, and sedimentary input, biological uptake and remineralization of Cu, reversible scavenging of Cu, and conversion of Cu between a labile species which is available for biological uptake and scavenging, and an inert phase of Cu which is not. The optimized model produces a good fit to global Cu observations, and highlights the key processes which control Cu distributions in the global ocean. The nearly linear increase in Cu concentrations with depth, which are observed throughout the oceans, can be achieved through either reversible scavenging or a sedimentary source, though models without either process yield a nonlinear vertical distribution. The simulated Cu in the Arctic Ocean is comparable with observational data only when there is high input to support the high surface Arctic Cu concentrations, and no or little scavenging so that Cu concentrations do not increase with depth as in other ocean basins. We find that Cu accumulates along the conveyor belt, with a higher concentration in the deep Pacific Ocean compared to the deep Atlantic Ocean, but that the relatively small concentration difference between these two ocean basins requires significantly higher external Cu inputs to the Atlantic. In addition to matching total Cu concentrations, our model is optimized to match observations of inert Cu in the North Pacific, yielding labile Cu concentrations which remain relatively constant in the water column, with increases near the seafloor, while inert Cu accumulates with the aging of water mass. We find that rivers, mineral dust, and nepheloid layer particles must each contribute with a comparable magnitude to the oceanic Cu reservoir, leading to the estimated residence time of 2,200 years. 

![Cu](/files/Cu1.jpg)
![Cu2](/files/Cu2.jpg)
